baseurl = "http://nekocode.github.io/"
languageCode = "zh-CN"
title = "nekocode"
theme = "hyde"

[params]
	description = "full statck developer"
	#disqusShortname = "spf13"

[[menu.main]]
	Name = "Zhihu Column"
	Url = "http://zhuanlan.zhihu.com/kotandroid"