baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "nekocode"
builddrafts = false
theme = "hyde"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "full stack developer"
  author = "Nikola Tesla"