baseurl = "http://www.nekocode.cn/"
languageCode = "en-us"
title = "nekocode"
theme = "hyde"

[params]
	description = "full statck developer"
	#disqusShortname = "spf13"

[[menu.main]]
	Name = "git@osc"
	Url = "http://git.oschina.net/nekocode"